// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTS1S6YnE_oogBfSfVnjySxa665QGRFH0',
    appId: '1:846678360221:web:e9fa6bf45d5625f4755474',
    messagingSenderId: '846678360221',
    projectId: 'sports-hub-92b8f',
    authDomain: 'sports-hub-92b8f.firebaseapp.com',
    storageBucket: 'sports-hub-92b8f.firebasestorage.app',
    measurementId: 'G-3FXTBFEJ2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbnjvjCHkTzLoqX5OjVW0xf73ElNyvtQ',
    appId: '1:846678360221:android:20068e2a53a4ca50755474',
    messagingSenderId: '846678360221',
    projectId: 'sports-hub-92b8f',
    storageBucket: 'sports-hub-92b8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt35pztCWeCWSQ9hEqNb7kS1PnT6XM2Ro',
    appId: '1:846678360221:ios:1f79bc2c62aad3b8755474',
    messagingSenderId: '846678360221',
    projectId: 'sports-hub-92b8f',
    storageBucket: 'sports-hub-92b8f.firebasestorage.app',
    iosBundleId: 'com.example.eStore',
  );
}
